language: c

sudo: required

services:
    - docker

before_install:
    - docker pull dlilien/elmerreplacements

install:
    - docker run dlilien/elmerreplacements

script:
    - docker run dlilien/elmerreplacements
