language: c

sudo: required

services:
    - docker

install:
    - docker pull dlilien/elmerreplacements

script:
    - docker run dlilien/elmerreplacements /bin/sh -c "git remote set-url origin http://www.github.com/dlilien/elmerreplacements.git; git pull; make all; make test"
