language: c

sudo: required

services:
    - docker

install:
    - docker pull dlilien/elmerreplacements

script:
    - docker run dlilien/elmerreplacements /bin/sh -c "git pull; make all; make test"
