language: c

sudo: required

services:
    - docker

before_install:
    - docker pull dlilien/elmerreplacements

install:
    - docker run  dlilien/elmerreplacements

script:
    - docker run  dlilien/elmerreplacements
    # - docker run dlilien/elmerreplacements /bin/sh -c "make test"
