#!/bin/sh -f

if test "$ELMER_LIB" = ""; then
  if  test "$ELMER_HOME" = ""; then
     echo "No lib no home"
     LIBDIR=/u/dlilien/sw/elmer/haswell_install/share/elmersolver/../../lib/elmersolver
     INCLUDE=/u/dlilien/sw/elmer/haswell_install/share/elmersolver/include
  else
     echo "Home no lib"
     LIBDIR=$ELMER_HOME/lib/elmersolver
     LIBDIR2=$ELMER_HOME/lib/
     INCLUDE=$ELMER_HOME/share/elmersolver/include
  fi
else
  echo "Found lib"
  LIBDIR=$ELMER_LIB
  INCLUDE=$ELMER_LIB/../include
fi

if test "$ELMER_Fortran_COMPILER" = ""; then
    THISHOST=$(hostname)
  if test $THISHOST = "loki.ess.washington.edu"; then
      FC=/usr/bin/gfortran
  else
      if [ -d /nasa/intel/Compiler ]; then
        FC=/nasa/intel/Compiler/2015.3.187/composer_xe_2015.3.187/bin/intel64/ifort
       else
        FC=/usr/bin/gfortran
  fi
else
  FC=$ELMER_Fortran_COMPILER
fi

echo $LIBDIR
echo $ELMER_HOME

cmd="$FC $*    -DCONTIG=,CONTIGUOUS -DHAVE_EXECUTECOMMANDLINE -DUSE_ISO_C_BINDINGS -DUSE_ARPACK -O2 -g -fPIC -shared -i_dynamic -nofor_main -I$INCLUDE -L$LIBDIR -shared -lelmersolver"
printf "%s " $cmd
printf "\n"
$FC $*  -DCONTIG=,CONTIGUOUS -DHAVE_EXECUTECOMMANDLINE -DUSE_ISO_C_BINDINGS -DUSE_ARPACK -O2 -fPIC -I$INCLUDE -L$LIBDIR
